### ISSUE TITLE
Consider passwords support; limitations of position-based CLI args

### ISSUE THREAD

**Issue by homeworkprod** [lf94/jyoti#1]
Hi @lf94, a nice project you have here! It checks the right boxes with me to take a closer look. :)

Having worked on some IRC tools myself, the position-based CLI you chose for your bot instantly reminds me of the struggles I had with adding more features people requested (to be able to integrate a bot in their environments):
- channel passwords
- server passwords
- server SSL

So, I guess I just like to suggest to you to keep those in mind.

They are doable as CLI options, but I myself went with a configuration file at some point (done in [Weitersager](https://github.com/homeworkprod/weitersager/), and actually ongoing these days in [syslog2IRC](https://github.com/homeworkprod/syslog2irc)) – to keep passwords out of CLI history and process lists, to ease version control, and to enable more structurally complex application-specific configuration.

Maybe considering this early can save you some headaches later on.

**Comment by lf94** [comment]
For sure positional based arguments are not great, and I agree named is much better. I didn't go with named because it would've added unnecessary code. The project is very hackable, so it'd be extremely trivial to add in passwords.

I didn't add in server SSL because it would require a lot more code. The project is zero dependency.

Thanks for the comments!

**Comment by homeworkprod** [comment]
Fair enough!
